# Generated by Django 3.1.7 on 2021-03-28 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
                ('records', models.ManyToManyField(to='users.Record')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='user_login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_records', to='users.user'),
        ),
    ]
